# glibc
PREFERRED_VERSION_cross-localedef-native ?= "2.27"
PREFERRED_VERSION_glibc ?= "2.27"
PREFERRED_VERSION_glibc-locale ?= "2.27"
PREFERRED_VERSION_glibc-mtrace ?= "2.27"
PREFERRED_VERSION_glibc-scripts ?= "2.27"
PREFERRED_VERSION_nativesdk-glibc ?= "2.27"
PREFERRED_VERSION_nativesdk-glibc-locale ?= "2.27"

# NOTE: Use the following template to append entries
# <PACKAGENAME>
# PREFERRED_VERSION_<PACKAGENAME> ?= "<VERSION>"
