name: ci

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Setup
        run: |
          sudo apt-get install -y fd-find
          pip install -r requirements.txt
      - name: oelint-adv
        run: fdfind -E "packagegroup*.bb" -e bb -e bbappend . --ignore-file .oelint-ignore -X oelint-adv
